//! Current schema bootstrap, root classification, and publication.
//!
//! Bootstrap owns the stable lock state machine and exact filesystem/SQLite
//! identities. It never adopts an unbound artifact.

use super::*;

/// Creates or resumes the direct current schema-15 epoch. A non-current root is
/// rejected by the bootstrap classifier before any current database open.
pub fn create_current(
    path: &Path,
    id_generator: &dyn IdGenerator,
) -> Result<CurrentState, StateError> {
    let mut no_op = no_bootstrap_checkpoint;
    bootstrap_current(path, Some(id_generator), &mut no_op)
}

/// Opens or resumes an exact current-format bootstrap. No identifier is
/// generated by this path: a non-empty root must carry all identities in its
/// existing stable bootstrap lock.
pub fn open_current(root: &StateRoot) -> Result<CurrentState, StateError> {
    let mut no_op = no_bootstrap_checkpoint;
    bootstrap_current(root.base(), None, &mut no_op)
}

/// Runs direct current bootstrap with a deterministic interruption hook. This
/// is crate-local so acceptance tests can prove every restart boundary while
/// production callers remain on the no-op [`create_current`] path.
#[cfg(test)]
pub(crate) fn create_current_with_checkpoint_hook(
    path: &Path,
    id_generator: &dyn IdGenerator,
    hook: BootstrapCheckpointHook<'_>,
) -> Result<CurrentState, StateError> {
    bootstrap_current(path, Some(id_generator), hook)
}

#[allow(
    clippy::unnecessary_wraps,
    reason = "The no-op production hook shares the fallible test-hook contract."
)]
pub(super) fn no_bootstrap_checkpoint(_checkpoint: BootstrapCheckpoint) -> Result<(), StateError> {
    Ok(())
}

pub(super) fn bootstrap_current(
    path: &Path,
    id_generator: Option<&dyn IdGenerator>,
    hook: BootstrapCheckpointHook<'_>,
) -> Result<CurrentState, StateError> {
    let initial = classify_current_root(path)?;
    if matches!(initial, CurrentRootClassification::Absent) {
        let generator = id_generator.ok_or(StateError::FreshStateRequired)?;
        create_private_fresh_root(path)?;
        return bootstrap_current(path, Some(generator), hook);
    }
    if matches!(initial, CurrentRootClassification::Empty) {
        let generator = id_generator.ok_or(StateError::FreshStateRequired)?;
        let root_metadata =
            fs::symlink_metadata(path).map_err(|error| StateError::io(path, error))?;
        let root_identity = bootstrap_file_identity(&root_metadata);
        let lock = BootstrapLease::create(path, root_identity, generator)?;
        return finish_current_bootstrap(lock, hook);
    }

    let root_metadata = fs::symlink_metadata(path).map_err(|error| StateError::io(path, error))?;
    let root_identity = bootstrap_file_identity(&root_metadata);
    let lock = BootstrapLease::acquire(path, root_identity)?;
    finish_current_bootstrap(lock, hook)
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum CurrentRootClassification {
    Absent,
    Empty,
    NonEmpty,
}

/// Performs only no-follow metadata and bounded directory enumeration. A
/// non-empty root is never made current by this classifier: the exact
/// existing bootstrap lock is required before any current database open.
pub(crate) fn classify_current_root(path: &Path) -> Result<CurrentRootClassification, StateError> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(CurrentRootClassification::Absent);
        }
        Err(error) => return Err(StateError::io(path, error)),
    };
    if !metadata.is_dir() || metadata.file_type().is_symlink() {
        return Err(StateError::FreshRootRejected(
            FreshRootRejection::NotDirectory,
        ));
    }
    if !is_private_owner_directory(&metadata) {
        return Err(StateError::FreshRootRejected(
            FreshRootRejection::NonPrivateDirectory,
        ));
    }
    let canonical = fs::canonicalize(path).map_err(|error| StateError::io(path, error))?;
    if canonical != path {
        return Err(StateError::FreshRootRejected(
            FreshRootRejection::NonCanonicalDirectory,
        ));
    }
    let mut count = 0_u16;
    let mut names = Vec::new();
    for entry in fs::read_dir(path).map_err(|error| StateError::io(path, error))? {
        let entry = entry.map_err(|error| StateError::io(path, error))?;
        count = count.saturating_add(1);
        if count > 256 {
            return Err(StateError::FreshRootRejected(
                FreshRootRejection::UnknownArtifact,
            ));
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| StateError::FreshRootRejected(FreshRootRejection::UnknownArtifact))?;
        names.push(name);
    }
    if names.is_empty() {
        return Ok(CurrentRootClassification::Empty);
    }
    // The current root is allowed to contain only the stable bootstrap
    // authority, current database/provisional artifacts, current runtime and
    // presentation namespaces, and one precommitted opaque staging name.
    // Unknown names remain refusal evidence; no legacy parser is consulted.
    let has_lock = names.iter().any(|name| name == BOOTSTRAP_LOCK_FILE);
    if !has_lock {
        // A bounded raw header is safe even before the current lock is held.
        // This lets an old or future SQLite epoch be refused from its
        // identity alone, without opening SQLite or inspecting legacy
        // process/presentation state. An exact current header still needs
        // the existing lock before any current database open.
        let database = path.join("host.sqlite");
        if names.iter().any(|name| name == "host.sqlite") {
            let identity = read_raw_schema_identity(&database)?;
            if identity.user_version < HOST_SCHEMA_VERSION {
                return Err(StateError::HostStateResetRequired(identity.user_version));
            }
            if identity.user_version > HOST_SCHEMA_VERSION {
                return Err(StateError::UnsupportedFutureHostSchema(
                    identity.user_version,
                ));
            }
            if identity.application_id != HOST_APPLICATION_ID {
                return Err(StateError::MalformedHostSchema);
            }
        }
        if names
            .iter()
            .any(|name| is_retired_client_artifact(name) || name == "transition.lock")
        {
            return Err(StateError::StateRecoveryRequired(
                StateRecoveryReason::UnknownFreshRootArtifact,
            ));
        }
        return Err(StateError::MissingBootstrapLock);
    }
    for name in names {
        if name == BOOTSTRAP_LOCK_FILE
            || name == "host.sqlite"
            || name == PROVISIONAL_LOCK_FILE
            || name == "run"
            || name == "presentation"
            || name.starts_with(BOOTSTRAP_STAGE_PREFIX)
        {
            continue;
        }
        return Err(
            if is_retired_client_artifact(&name) || name == "transition.lock" {
                StateError::StateRecoveryRequired(StateRecoveryReason::UnknownFreshRootArtifact)
            } else {
                StateError::FreshRootRejected(FreshRootRejection::UnknownArtifact)
            },
        );
    }
    Ok(CurrentRootClassification::NonEmpty)
}

pub(super) fn bootstrap_file_identity(metadata: &fs::Metadata) -> BootstrapFileIdentity {
    #[cfg(unix)]
    {
        use std::os::unix::fs::MetadataExt;
        BootstrapFileIdentity {
            device: metadata.dev(),
            inode: metadata.ino(),
        }
    }
    #[cfg(not(unix))]
    {
        let _ = metadata;
        BootstrapFileIdentity {
            device: 0,
            inode: 0,
        }
    }
}

/// Opens the exact root directory without following a final symlink.  The
/// descriptor remains held for the complete bootstrap operation so subsequent
/// artifact effects stay anchored to the directory that was classified.
pub(super) fn open_bootstrap_root_directory(root: &Path) -> Result<File, StateError> {
    #[cfg(not(target_os = "linux"))]
    {
        let _ = root;
        return Err(StateError::InvalidBootstrapLock);
    }
    let mut options = OpenOptions::new();
    options.read(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.custom_flags(nix::libc::O_CLOEXEC | nix::libc::O_DIRECTORY | nix::libc::O_NOFOLLOW);
    }
    let directory = options
        .open(root)
        .map_err(|error| StateError::io(root, error))?;
    let metadata = directory
        .metadata()
        .map_err(|error| StateError::io(root, error))?;
    if !metadata.is_dir() || !is_private_owner_directory(&metadata) {
        return Err(StateError::InvalidBootstrapLock);
    }
    #[cfg(target_os = "linux")]
    {
        // `/proc/self/fd` is the anchor that keeps effects tied to the held
        // root object. Without procfs, no current bootstrap operation is
        // safe, even though the root descriptor itself was opened.
        fs::canonicalize(bootstrap_root_path(root, &directory))
            .map_err(|error| StateError::io(root, error))?;
    }
    Ok(directory)
}

/// Resolve a top-level artifact through the held root directory descriptor.
/// On Linux `/proc/self/fd` preserves the exact directory object across a
/// rename/replacement of the user-visible root path. Unsupported targets use a
/// sentinel only so accidental path-based effects cannot compile into the
/// current bootstrap route; opening the held root already fails closed there.
pub(super) fn bootstrap_root_path(root: &Path, directory: &File) -> PathBuf {
    #[cfg(target_os = "linux")]
    {
        let _ = root;
        PathBuf::from(format!("/proc/self/fd/{}", directory.as_raw_fd()))
    }
    #[cfg(not(target_os = "linux"))]
    {
        let _ = (root, directory);
        PathBuf::from("/__wsnav_current_procfs_required__")
    }
}

pub(super) fn bootstrap_root_artifact_path(root: &Path, directory: &File, name: &str) -> PathBuf {
    bootstrap_root_path(root, directory).join(name)
}

pub(super) fn finish_current_bootstrap(
    mut lease: BootstrapLease,
    hook: BootstrapCheckpointHook<'_>,
) -> Result<CurrentState, StateError> {
    loop {
        match lease.record.phase {
            BootstrapPhase::RootReserved => {
                hook(BootstrapCheckpoint::RootReserved)?;
                lease.revalidate()?;
                let root = lease.held_root_path();
                validate_current_root_entries(&root)?;
                ensure_bootstrap_path_absent(&root, "host.sqlite")?;
                ensure_bootstrap_path_absent(&root, PROVISIONAL_LOCK_FILE)?;
                ensure_bootstrap_path_absent(&root, "run")?;
                ensure_bootstrap_path_absent(&root, "presentation")?;
                ensure_named_stage_absent(&root, None)?;
                let stage_name = bootstrap_stage_name(&lease.record.bootstrap_generation)?;
                lease.transition_with(BootstrapPhase::DatabaseCreateReserved, |record| {
                    record.database_name = Some(stage_name);
                })?;
            }
            BootstrapPhase::DatabaseCreateReserved => {
                hook(BootstrapCheckpoint::DatabaseCreateReserved)?;
                lease.revalidate()?;
                let name = lease
                    .record
                    .database_name
                    .clone()
                    .ok_or(StateError::InvalidBootstrapLock)?;
                let root = lease.held_root_path();
                validate_current_root_entries(&root)?;
                ensure_named_stage_absent(&root, Some(&name))?;
                let path = lease.artifact_path(&name);
                ensure_bootstrap_path_absent(&root, "host.sqlite")?;
                ensure_bootstrap_path_absent(&root, PROVISIONAL_LOCK_FILE)?;
                ensure_bootstrap_path_absent(&root, "run")?;
                ensure_bootstrap_path_absent(&root, "presentation")?;
                if exact_artifact_metadata(&path)?.is_some() {
                    // There is no durable identity for this artifact. It may
                    // have been created before the process crashed, so it is
                    // deliberately effect-unknown and never adopted.
                    return Err(StateError::BootstrapEffectUnknown);
                }
                let file = create_private_database_file_at(&lease.root_directory, &name, &path)?;
                let identity = bootstrap_file_identity(
                    &file
                        .metadata()
                        .map_err(|error| StateError::io(&path, error))?,
                );
                drop(file);
                hook(BootstrapCheckpoint::DatabaseCreated)?;
                lease.transition_with(BootstrapPhase::DatabaseOwned, |record| {
                    record.database_device = Some(identity.device);
                    record.database_inode = Some(identity.inode);
                })?;
            }
            BootstrapPhase::DatabaseOwned => {
                hook(BootstrapCheckpoint::DatabaseOwned)?;
                bootstrap_initialize_database(&mut lease)?;
                hook(BootstrapCheckpoint::DatabaseInitialized)?;
                lease.transition(BootstrapPhase::DatabaseReady)?;
            }
            BootstrapPhase::DatabaseReady => {
                hook(BootstrapCheckpoint::DatabaseReady)?;
                bootstrap_publish_database(&mut lease)?;
                hook(BootstrapCheckpoint::DatabasePublished)?;
                lease.transition_with(BootstrapPhase::ProvisionalPending, |record| {
                    record.database_name = Some("host.sqlite".to_owned());
                })?;
            }
            BootstrapPhase::ProvisionalPending => {
                hook(BootstrapCheckpoint::ProvisionalPending)?;
                let provisional_identity = bootstrap_install_provisional(&mut lease, hook)?;
                lease.transition_with(BootstrapPhase::Ready, |record| {
                    record.provisional_device = Some(provisional_identity.device);
                    record.provisional_inode = Some(provisional_identity.inode);
                })?;
            }
            BootstrapPhase::Ready => {
                hook(BootstrapCheckpoint::Ready)?;
                return bootstrap_open_ready(lease);
            }
        }
    }
}

impl BootstrapLease {
    fn create(
        root: &Path,
        root_identity: BootstrapFileIdentity,
        id_generator: &dyn IdGenerator,
    ) -> Result<Self, StateError> {
        let root_directory = open_bootstrap_root_directory(root)?;
        let opened_root_identity = bootstrap_file_identity(
            &root_directory
                .metadata()
                .map_err(|error| StateError::io(root, error))?,
        );
        if opened_root_identity != root_identity {
            return Err(StateError::InvalidBootstrapLock);
        }
        let visible_root_identity = bootstrap_file_identity(
            &fs::symlink_metadata(root).map_err(|error| StateError::io(root, error))?,
        );
        if visible_root_identity != root_identity {
            return Err(StateError::InvalidBootstrapLock);
        }
        let lock_path = root.join(BOOTSTRAP_LOCK_FILE);
        let lock_scoped_path =
            bootstrap_root_artifact_path(root, &root_directory, BOOTSTRAP_LOCK_FILE);
        let file = open_private_bootstrap_file_at(
            &root_directory,
            BOOTSTRAP_LOCK_FILE,
            &lock_scoped_path,
            true,
        )?;
        let lock_identity = bootstrap_file_identity(
            &file
                .metadata()
                .map_err(|error| StateError::io(&lock_path, error))?,
        );
        let file = nix::fcntl::Flock::lock(file, nix::fcntl::FlockArg::LockExclusiveNonblock)
            .map_err(|(_file, _error)| StateError::BootstrapLockBusy)?;
        let host_id = HostId::from(id_generator.uuid()).to_string();
        let generation = id_generator.uuid().to_string();
        let record = BootstrapRecordBody {
            format_version: BOOTSTRAP_LOCK_FORMAT_VERSION,
            schema_version: HOST_SCHEMA_VERSION,
            application_id: HOST_APPLICATION_ID,
            host_id,
            bootstrap_generation: generation,
            root_device: root_identity.device,
            root_inode: root_identity.inode,
            phase: BootstrapPhase::RootReserved,
            database_name: None,
            database_device: None,
            database_inode: None,
            provisional_device: None,
            provisional_inode: None,
        };
        let mut lease = Self {
            root: root.to_path_buf(),
            lock_path,
            root_directory,
            root_identity,
            lock_identity,
            record,
            file,
        };
        lease.write_record()?;
        Ok(lease)
    }

    fn acquire(root: &Path, root_identity: BootstrapFileIdentity) -> Result<Self, StateError> {
        let root_directory = open_bootstrap_root_directory(root)?;
        let opened_root_identity = bootstrap_file_identity(
            &root_directory
                .metadata()
                .map_err(|error| StateError::io(root, error))?,
        );
        if opened_root_identity != root_identity {
            return Err(StateError::InvalidBootstrapLock);
        }
        let visible_root_identity = bootstrap_file_identity(
            &fs::symlink_metadata(root).map_err(|error| StateError::io(root, error))?,
        );
        if visible_root_identity != root_identity {
            return Err(StateError::InvalidBootstrapLock);
        }
        let lock_path = root.join(BOOTSTRAP_LOCK_FILE);
        let lock_scoped_path =
            bootstrap_root_artifact_path(root, &root_directory, BOOTSTRAP_LOCK_FILE);
        let metadata =
            exact_artifact_metadata(&lock_scoped_path)?.ok_or(StateError::MissingBootstrapLock)?;
        if !metadata.is_file() || !is_private_owner_file(&metadata) {
            return Err(StateError::InvalidBootstrapLock);
        }
        let file = open_private_bootstrap_file_at(
            &root_directory,
            BOOTSTRAP_LOCK_FILE,
            &lock_scoped_path,
            false,
        )?;
        let lock_identity = bootstrap_file_identity(
            &file
                .metadata()
                .map_err(|error| StateError::io(&lock_path, error))?,
        );
        if lock_identity != bootstrap_file_identity(&metadata) {
            return Err(StateError::InvalidBootstrapLock);
        }
        let file = nix::fcntl::Flock::lock(file, nix::fcntl::FlockArg::LockExclusiveNonblock)
            .map_err(|(_file, _error)| StateError::BootstrapLockBusy)?;
        let record = read_bootstrap_record(&file, &lock_path)?;
        let lease = Self {
            root: root.to_path_buf(),
            lock_path,
            root_directory,
            root_identity,
            lock_identity,
            record,
            file,
        };
        lease.revalidate()?;
        Ok(lease)
    }

    fn revalidate(&self) -> Result<(), StateError> {
        self.revalidate_identity()?;
        if read_bootstrap_record(&self.file, &self.lock_path)? != self.record {
            return Err(StateError::InvalidBootstrapLock);
        }
        Ok(())
    }

    fn revalidate_identity(&self) -> Result<(), StateError> {
        let root_metadata =
            fs::symlink_metadata(&self.root).map_err(|error| StateError::io(&self.root, error))?;
        let held_root_metadata = self
            .root_directory
            .metadata()
            .map_err(|error| StateError::io(&self.root, error))?;
        let lock_path = self.artifact_path(BOOTSTRAP_LOCK_FILE);
        let lock_metadata = fs::symlink_metadata(&lock_path)
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        if !root_metadata.is_dir()
            || !is_private_owner_directory(&root_metadata)
            || bootstrap_file_identity(&root_metadata) != self.root_identity
            || !held_root_metadata.is_dir()
            || !is_private_owner_directory(&held_root_metadata)
            || bootstrap_file_identity(&held_root_metadata) != self.root_identity
            || !lock_metadata.is_file()
            || !is_private_owner_file(&lock_metadata)
            || bootstrap_file_identity(&lock_metadata) != self.lock_identity
        {
            return Err(StateError::InvalidBootstrapLock);
        }
        if self.record.root_device != self.root_identity.device
            || self.record.root_inode != self.root_identity.inode
        {
            return Err(StateError::InvalidBootstrapLock);
        }
        let opened = self
            .file
            .metadata()
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        if !opened.is_file()
            || !is_private_owner_file(&opened)
            || bootstrap_file_identity(&opened) != self.lock_identity
        {
            return Err(StateError::InvalidBootstrapLock);
        }
        Ok(())
    }

    fn artifact_path(&self, name: &str) -> PathBuf {
        bootstrap_root_artifact_path(&self.root, &self.root_directory, name)
    }

    fn held_root_path(&self) -> PathBuf {
        bootstrap_root_path(&self.root, &self.root_directory)
    }

    fn sync_root(&self) -> Result<(), StateError> {
        self.root_directory
            .sync_all()
            .map_err(|error| StateError::io(&self.root, error))
    }

    fn transition(&mut self, phase: BootstrapPhase) -> Result<(), StateError> {
        self.transition_with(phase, |_| {})
    }

    fn transition_with(
        &mut self,
        phase: BootstrapPhase,
        update: impl FnOnce(&mut BootstrapRecordBody),
    ) -> Result<(), StateError> {
        self.revalidate()?;
        validate_bootstrap_transition(&self.record, phase)?;
        update(&mut self.record);
        self.record.phase = phase;
        self.write_record()?;
        self.revalidate()
    }

    fn write_record(&mut self) -> Result<(), StateError> {
        // `transition` performs a full record revalidation before changing
        // `self.record`; creation starts with an intentionally empty file.
        // Keep this write bound to the held inode without trying to parse the
        // old record after the in-memory phase has advanced.
        self.revalidate_identity()?;
        let bytes = encode_bootstrap_record(&self.record)?;
        self.file
            .set_len(0)
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        self.file
            .seek(SeekFrom::Start(0))
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        self.file
            .write_all(&bytes)
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        self.file
            .sync_all()
            .map_err(|error| StateError::io(&self.lock_path, error))?;
        self.sync_root()
    }
}

pub(super) fn validate_bootstrap_transition(
    record: &BootstrapRecordBody,
    next: BootstrapPhase,
) -> Result<(), StateError> {
    let valid = matches!(
        (record.phase, next),
        (
            BootstrapPhase::RootReserved,
            BootstrapPhase::DatabaseCreateReserved
        ) | (
            BootstrapPhase::DatabaseCreateReserved,
            BootstrapPhase::DatabaseOwned
        ) | (BootstrapPhase::DatabaseOwned, BootstrapPhase::DatabaseReady)
            | (
                BootstrapPhase::DatabaseReady,
                BootstrapPhase::ProvisionalPending
            )
            | (BootstrapPhase::ProvisionalPending, BootstrapPhase::Ready)
    );
    if valid {
        Ok(())
    } else {
        Err(StateError::InvalidBootstrapLock)
    }
}

pub(super) fn encode_bootstrap_record(record: &BootstrapRecordBody) -> Result<Vec<u8>, StateError> {
    validate_bootstrap_record(record)?;
    let body = serde_json::to_vec(record).map_err(|_| StateError::InvalidBootstrapLock)?;
    let checksum = sha256_hex(&body);
    let wire = BootstrapRecordWire {
        body: record.clone(),
        checksum,
    };
    let mut bytes = serde_json::to_vec(&wire).map_err(|_| StateError::InvalidBootstrapLock)?;
    bytes.push(b'\n');
    if bytes.len() > MAX_BOOTSTRAP_LOCK_BYTES {
        return Err(StateError::InvalidBootstrapLock);
    }
    Ok(bytes)
}

pub(super) fn read_bootstrap_record(
    file: &File,
    path: &Path,
) -> Result<BootstrapRecordBody, StateError> {
    let mut duplicate = file
        .try_clone()
        .map_err(|error| StateError::io(path, error))?;
    duplicate
        .seek(SeekFrom::Start(0))
        .map_err(|error| StateError::io(path, error))?;
    let mut bytes = Vec::new();
    duplicate
        .take(u64::try_from(MAX_BOOTSTRAP_LOCK_BYTES + 1).unwrap_or(u64::MAX))
        .read_to_end(&mut bytes)
        .map_err(|error| StateError::io(path, error))?;
    if bytes.len() > MAX_BOOTSTRAP_LOCK_BYTES {
        return Err(StateError::InvalidBootstrapLock);
    }
    let wire: BootstrapRecordWire =
        serde_json::from_slice(&bytes).map_err(|_| StateError::InvalidBootstrapLock)?;
    let body = serde_json::to_vec(&wire.body).map_err(|_| StateError::InvalidBootstrapLock)?;
    if wire.checksum != sha256_hex(&body) {
        return Err(StateError::InvalidBootstrapLock);
    }
    validate_bootstrap_record(&wire.body)?;
    Ok(wire.body)
}

pub(super) fn validate_bootstrap_record(record: &BootstrapRecordBody) -> Result<(), StateError> {
    let host_id = Uuid::parse_str(&record.host_id).ok();
    let bootstrap_generation = Uuid::parse_str(&record.bootstrap_generation).ok();
    if record.format_version != BOOTSTRAP_LOCK_FORMAT_VERSION
        || record.schema_version != HOST_SCHEMA_VERSION
        || record.application_id != HOST_APPLICATION_ID
        || host_id.is_none_or(|value| value.is_nil())
        || bootstrap_generation.is_none_or(|value| value.is_nil())
        || record.root_inode == 0
        || record
            .database_name
            .as_deref()
            .is_some_and(|name| name != "host.sqlite" && !is_bootstrap_stage_name(name))
    {
        return Err(StateError::InvalidBootstrapLock);
    }
    match record.phase {
        BootstrapPhase::RootReserved => {
            if record.database_name.is_some()
                || record.database_device.is_some()
                || record.database_inode.is_some()
                || record.provisional_device.is_some()
                || record.provisional_inode.is_some()
            {
                return Err(StateError::InvalidBootstrapLock);
            }
        }
        BootstrapPhase::DatabaseCreateReserved => {
            if record.database_name.as_deref()
                != Some(bootstrap_stage_name(&record.bootstrap_generation)?.as_str())
                || record.database_device.is_some()
                || record.database_inode.is_some()
                || record.provisional_device.is_some()
                || record.provisional_inode.is_some()
            {
                return Err(StateError::InvalidBootstrapLock);
            }
        }
        BootstrapPhase::DatabaseOwned | BootstrapPhase::DatabaseReady => {
            if record.database_name.as_deref()
                != Some(bootstrap_stage_name(&record.bootstrap_generation)?.as_str())
                || record.database_device.is_none()
                || record.database_inode.is_none_or(|inode| inode == 0)
                || record.provisional_device.is_some()
                || record.provisional_inode.is_some()
            {
                return Err(StateError::InvalidBootstrapLock);
            }
        }
        BootstrapPhase::ProvisionalPending => {
            if record.database_name.as_deref() != Some("host.sqlite")
                || record.database_device.is_none()
                || record.database_inode.is_none_or(|inode| inode == 0)
                || record.provisional_device.is_some()
                || record.provisional_inode.is_some()
            {
                return Err(StateError::InvalidBootstrapLock);
            }
        }
        BootstrapPhase::Ready => {
            if record.database_name.as_deref() != Some("host.sqlite")
                || record.database_device.is_none()
                || record.database_inode.is_none_or(|inode| inode == 0)
                || record.provisional_device.is_none()
                || record.provisional_inode.is_none_or(|inode| inode == 0)
            {
                return Err(StateError::InvalidBootstrapLock);
            }
        }
    }
    Ok(())
}

pub(super) fn is_bootstrap_stage_name(name: &str) -> bool {
    name.strip_prefix(BOOTSTRAP_STAGE_PREFIX)
        .is_some_and(|suffix| {
            suffix.len() == 32
                && suffix
                    .bytes()
                    .all(|byte| byte.is_ascii_digit() || matches!(byte, b'a'..=b'f'))
        })
}

pub(super) fn bootstrap_stage_name(generation: &str) -> Result<String, StateError> {
    let uuid = Uuid::parse_str(generation).map_err(|_| StateError::InvalidBootstrapLock)?;
    if uuid.is_nil() {
        return Err(StateError::InvalidBootstrapLock);
    }
    Ok(format!("{BOOTSTRAP_STAGE_PREFIX}{}", uuid.simple()))
}

pub(super) fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut encoded = String::with_capacity(64);
    for byte in digest {
        let _ = write!(&mut encoded, "{byte:02x}");
    }
    encoded
}

#[allow(
    clippy::too_many_lines,
    reason = "the bootstrap database boundary keeps every direct-schema and identity check auditable"
)]
pub(super) fn bootstrap_initialize_database(lease: &mut BootstrapLease) -> Result<(), StateError> {
    lease.revalidate()?;
    let root = lease.held_root_path();
    validate_current_root_entries(&root)?;
    let name = lease
        .record
        .database_name
        .clone()
        .ok_or(StateError::InvalidBootstrapLock)?;
    ensure_named_stage_absent(&root, Some(&name))?;
    let path = lease.artifact_path(&name);
    ensure_bootstrap_path_absent(&root, "host.sqlite")?;
    ensure_bootstrap_path_absent(&root, PROVISIONAL_LOCK_FILE)?;
    ensure_bootstrap_path_absent(&root, "run")?;
    ensure_bootstrap_path_absent(&root, "presentation")?;
    let metadata = exact_artifact_metadata(&path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    let expected = BootstrapFileIdentity {
        device: lease
            .record
            .database_device
            .ok_or(StateError::InvalidBootstrapLock)?,
        inode: lease
            .record
            .database_inode
            .ok_or(StateError::InvalidBootstrapLock)?,
    };
    if !metadata.is_file()
        || !is_private_owner_file(&metadata)
        || bootstrap_file_identity(&metadata) != expected
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    ensure_database_sidecars_absent(&path)?;
    let size = metadata.len();
    if size == 0 {
        let mut database = open_bootstrap_database(lease, &name, &path, expected)?;
        configure_current_connection(&database.connection)?;
        database
            .connection
            .execute_batch("PRAGMA journal_mode = DELETE; PRAGMA synchronous = FULL;")
            .map_err(StateError::Sqlite)?;
        let transaction = database
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(StateError::Sqlite)?;
        transaction
            .execute_batch(HOST_SCHEMA_15_SQL)
            .map_err(StateError::Sqlite)?;
        transaction
            .execute(
                "INSERT INTO host_identity (
                    singleton, host_id, registry_generation, schema_version
                 ) VALUES (1, ?1, ?2, ?3)",
                params![
                    lease.record.host_id,
                    lease.record.bootstrap_generation,
                    HOST_SCHEMA_VERSION,
                ],
            )
            .map_err(StateError::Sqlite)?;
        transaction
            .execute(
                "INSERT INTO host_operational_metadata (
                    singleton, bootstrap_host_id, bootstrap_generation,
                    provisional_lease_generation, provisional_lock_phase,
                    provisional_lock_device, provisional_lock_inode
                 ) VALUES (1, ?1, ?2, 1, 'pending', NULL, NULL)",
                params![lease.record.host_id, lease.record.bootstrap_generation],
            )
            .map_err(StateError::Sqlite)?;
        transaction
            .execute("PRAGMA application_id = 0x57534e56", [])
            .map_err(StateError::Sqlite)?;
        transaction
            .execute("PRAGMA user_version = 15", [])
            .map_err(StateError::Sqlite)?;
        validate_schema15(&transaction)?;
        transaction.commit().map_err(StateError::Sqlite)?;
        drop(database);
        let identity = read_raw_schema_identity(&path)?;
        if identity.application_id != HOST_APPLICATION_ID
            || identity.user_version != HOST_SCHEMA_VERSION
        {
            return Err(StateError::MalformedHostSchema);
        }
    } else {
        let identity = read_raw_schema_identity(&path)?;
        if identity.application_id != HOST_APPLICATION_ID
            || identity.user_version != HOST_SCHEMA_VERSION
        {
            return Err(StateError::BootstrapArtifactMismatch);
        }
        let database = open_bootstrap_database(lease, &name, &path, expected)?;
        configure_current_connection(&database.connection)?;
        validate_schema15(&database.connection)?;
        validate_bootstrap_database_identity(&database.connection, lease)?;
        drop(database);
    }
    lease.revalidate()?;
    let after = exact_artifact_metadata(&path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    if bootstrap_file_identity(&after) != expected {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    Ok(())
}

#[allow(
    clippy::too_many_lines,
    reason = "the bootstrap publication boundary keeps every identity and sync check auditable"
)]
pub(super) fn bootstrap_publish_database(lease: &mut BootstrapLease) -> Result<(), StateError> {
    lease.revalidate()?;
    let root = lease.held_root_path();
    validate_current_root_entries(&root)?;
    let stage_name = lease
        .record
        .database_name
        .clone()
        .ok_or(StateError::InvalidBootstrapLock)?;
    ensure_named_stage_absent(&root, Some(&stage_name))?;
    let stage_path = lease.artifact_path(&stage_name);
    let destination = lease.artifact_path("host.sqlite");
    ensure_bootstrap_path_absent(&root, PROVISIONAL_LOCK_FILE)?;
    ensure_bootstrap_path_absent(&root, "run")?;
    ensure_bootstrap_path_absent(&root, "presentation")?;
    let stage = exact_artifact_metadata(&stage_path)?;
    let final_file = exact_artifact_metadata(&destination)?;
    let expected = BootstrapFileIdentity {
        device: lease
            .record
            .database_device
            .ok_or(StateError::InvalidBootstrapLock)?,
        inode: lease
            .record
            .database_inode
            .ok_or(StateError::InvalidBootstrapLock)?,
    };
    match (stage, final_file) {
        (Some(stage), None) => {
            if !stage.is_file()
                || !is_private_owner_file(&stage)
                || bootstrap_file_identity(&stage) != expected
            {
                return Err(StateError::BootstrapArtifactMismatch);
            }
            let identity = read_raw_schema_identity(&stage_path)?;
            if identity.application_id != HOST_APPLICATION_ID
                || identity.user_version != HOST_SCHEMA_VERSION
            {
                return Err(StateError::BootstrapArtifactMismatch);
            }
            let database = open_bootstrap_database(lease, &stage_name, &stage_path, expected)?;
            configure_current_connection(&database.connection)?;
            validate_schema15(&database.connection)?;
            validate_bootstrap_database_identity(&database.connection, lease)?;
            drop(database);
            if exact_artifact_metadata(&stage_path.with_file_name(format!("{stage_name}-journal")))?
                .is_some()
                || exact_artifact_metadata(&stage_path.with_file_name(format!("{stage_name}-wal")))?
                    .is_some()
                || exact_artifact_metadata(&stage_path.with_file_name(format!("{stage_name}-shm")))?
                    .is_some()
            {
                return Err(StateError::BootstrapEffectUnknown);
            }
            let file = open_bootstrap_relative_file(
                &lease.root_directory,
                &stage_name,
                &stage_path,
                false,
            )?;
            let opened = file
                .metadata()
                .map_err(|error| StateError::io(&stage_path, error))?;
            if !opened.is_file()
                || !is_private_owner_file(&opened)
                || bootstrap_file_identity(&opened) != expected
            {
                return Err(StateError::BootstrapArtifactMismatch);
            }
            file.sync_all()
                .map_err(|error| StateError::io(&stage_path, error))?;
            drop(file);
            lease.revalidate()?;
            rename_bootstrap_database(&lease.root_directory, &stage_name, &destination)?;
            lease.sync_root()?;
            let final_metadata = exact_artifact_metadata(&destination)?
                .ok_or(StateError::BootstrapArtifactMismatch)?;
            if bootstrap_file_identity(&final_metadata) != expected {
                return Err(StateError::BootstrapArtifactMismatch);
            }
        }
        (None, Some(final_file)) => {
            if !final_file.is_file()
                || !is_private_owner_file(&final_file)
                || bootstrap_file_identity(&final_file) != expected
            {
                return Err(StateError::BootstrapArtifactMismatch);
            }
            let identity = read_raw_schema_identity(&destination)?;
            if identity.application_id != HOST_APPLICATION_ID
                || identity.user_version != HOST_SCHEMA_VERSION
            {
                return Err(StateError::BootstrapArtifactMismatch);
            }
            let database = open_bootstrap_database(lease, "host.sqlite", &destination, expected)?;
            configure_current_connection(&database.connection)?;
            validate_schema15(&database.connection)?;
            validate_bootstrap_database_identity(&database.connection, lease)?;
            drop(database);
        }
        (Some(_), Some(_)) => return Err(StateError::BootstrapEffectUnknown),
        (None, None) => return Err(StateError::BootstrapArtifactMismatch),
    }
    Ok(())
}

/// Ensures an owned database is bound to this bootstrap lease before it can
/// be published. A valid schema with another `HostId` or generation is still
/// foreign evidence, not an artifact this lease may adopt.
pub(super) fn validate_bootstrap_database_identity(
    connection: &Connection,
    lease: &BootstrapLease,
) -> Result<(), StateError> {
    let metadata: Option<BootstrapDatabaseMetadata> = connection
        .query_row(
            "SELECT host_identity.host_id, host_identity.registry_generation,
                    host_operational_metadata.bootstrap_host_id,
                    host_operational_metadata.bootstrap_generation,
                    host_operational_metadata.provisional_lock_phase,
                    host_operational_metadata.provisional_lease_generation,
                    host_operational_metadata.provisional_lock_device,
                    host_operational_metadata.provisional_lock_inode
             FROM host_identity
             JOIN host_operational_metadata
               ON host_operational_metadata.singleton = host_identity.singleton
             WHERE host_identity.singleton = 1",
            [],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                    row.get(7)?,
                ))
            },
        )
        .optional()
        .map_err(StateError::Sqlite)?;
    let Some((
        host_id,
        registry_generation,
        bootstrap_host_id,
        bootstrap_generation,
        phase,
        lease_generation,
        provisional_device,
        provisional_inode,
    )) = metadata
    else {
        return Err(StateError::BootstrapArtifactMismatch);
    };
    if host_id != lease.record.host_id
        || registry_generation != lease.record.bootstrap_generation
        || bootstrap_host_id != lease.record.host_id
        || bootstrap_generation != lease.record.bootstrap_generation
        || lease_generation <= 0
        || phase != "pending"
        || provisional_device.is_some()
        || provisional_inode.is_some()
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    Ok(())
}

#[allow(
    clippy::too_many_lines,
    reason = "the bootstrap provisional boundary keeps file and database ordering auditable"
)]
pub(super) fn bootstrap_install_provisional(
    lease: &mut BootstrapLease,
    hook: BootstrapCheckpointHook<'_>,
) -> Result<BootstrapFileIdentity, StateError> {
    lease.revalidate()?;
    let root = lease.held_root_path();
    validate_current_root_entries(&root)?;
    ensure_named_stage_absent(&root, None)?;
    ensure_bootstrap_path_absent(&root, "run")?;
    ensure_bootstrap_path_absent(&root, "presentation")?;
    let database_path = lease.artifact_path("host.sqlite");
    let database_metadata =
        exact_artifact_metadata(&database_path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    let expected_database = BootstrapFileIdentity {
        device: lease
            .record
            .database_device
            .ok_or(StateError::InvalidBootstrapLock)?,
        inode: lease
            .record
            .database_inode
            .ok_or(StateError::InvalidBootstrapLock)?,
    };
    if !database_metadata.is_file()
        || !is_private_owner_file(&database_metadata)
        || bootstrap_file_identity(&database_metadata) != expected_database
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let identity = read_raw_schema_identity(&database_path)?;
    if identity.application_id != HOST_APPLICATION_ID
        || identity.user_version != HOST_SCHEMA_VERSION
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let mut database =
        open_bootstrap_database(lease, "host.sqlite", &database_path, expected_database)?;
    configure_current_connection(&database.connection)?;
    validate_schema15(&database.connection)?;
    let metadata: (
        String,
        String,
        String,
        String,
        i64,
        String,
        Option<i64>,
        Option<i64>,
    ) = database
        .connection
        .query_row(
            "SELECT host_identity.host_id, host_identity.registry_generation,
                    host_operational_metadata.bootstrap_host_id,
                    host_operational_metadata.bootstrap_generation,
                    host_operational_metadata.provisional_lease_generation,
                    host_operational_metadata.provisional_lock_phase,
                    host_operational_metadata.provisional_lock_device,
                    host_operational_metadata.provisional_lock_inode
             FROM host_identity
             JOIN host_operational_metadata
               ON host_operational_metadata.singleton = host_identity.singleton
             WHERE host_identity.singleton = 1",
            [],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                    row.get(7)?,
                ))
            },
        )
        .map_err(StateError::Sqlite)?;
    if metadata.0 != lease.record.host_id
        || metadata.1 != lease.record.bootstrap_generation
        || metadata.2 != lease.record.host_id
        || metadata.3 != lease.record.bootstrap_generation
        || metadata.4 <= 0
        || !matches!(metadata.5.as_str(), "pending" | "ready")
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let expected_contents = provisional_lock_contents(&lease.record.host_id, metadata.4)?;
    let provisional_path = lease.artifact_path(PROVISIONAL_LOCK_FILE);
    let existing_provisional = exact_artifact_metadata(&provisional_path)?;
    if metadata.5 == "ready" && existing_provisional.is_none() {
        // A committed database-ready state without its precommitted lock
        // identity is the forbidden inverse recovery pair. Do not create a
        // replacement file merely because the path is vacant.
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let (file, known_provisional_identity) = if existing_provisional.is_none() {
        let mut file = open_private_provisional_file_at(
            &lease.root_directory,
            PROVISIONAL_LOCK_FILE,
            &provisional_path,
            true,
        )?;
        file.write_all(&expected_contents)
            .map_err(|error| StateError::io(&provisional_path, error))?;
        file.sync_all()
            .map_err(|error| StateError::io(&provisional_path, error))?;
        lease.sync_root()?;
        let identity =
            validate_provisional_lock_file(&file, &provisional_path, &expected_contents)?;
        hook(BootstrapCheckpoint::ProvisionalCreated)?;
        (file, identity)
    } else {
        let file = open_private_provisional_file_at(
            &lease.root_directory,
            PROVISIONAL_LOCK_FILE,
            &provisional_path,
            false,
        )?;
        let identity =
            validate_provisional_lock_file(&file, &provisional_path, &expected_contents)?;
        (file, identity)
    };
    let file = nix::fcntl::Flock::lock(file, nix::fcntl::FlockArg::LockExclusiveNonblock)
        .map_err(|(_file, _error)| StateError::ProvisionalLeaseBusy)?;
    let provisional_identity = bootstrap_file_identity(
        &file
            .metadata()
            .map_err(|error| StateError::io(&provisional_path, error))?,
    );
    if known_provisional_identity.device != provisional_identity.device
        || known_provisional_identity.inode != provisional_identity.inode
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let transitioned_pending = metadata.5 == "pending";
    if transitioned_pending {
        let transaction = database
            .connection
            .transaction_with_behavior(TransactionBehavior::Immediate)
            .map_err(StateError::Sqlite)?;
        let changed = transaction
            .execute(
                "UPDATE host_operational_metadata
                 SET provisional_lock_phase = 'ready',
                     provisional_lock_device = ?1,
                     provisional_lock_inode = ?2
                 WHERE singleton = 1
                   AND bootstrap_host_id = ?3
                   AND bootstrap_generation = ?4
                   AND provisional_lock_phase = 'pending'",
                params![
                    i64::try_from(provisional_identity.device)
                        .map_err(|_| StateError::BootstrapArtifactMismatch)?,
                    i64::try_from(provisional_identity.inode)
                        .map_err(|_| StateError::BootstrapArtifactMismatch)?,
                    lease.record.host_id,
                    lease.record.bootstrap_generation,
                ],
            )
            .map_err(StateError::Sqlite)?;
        if changed != 1 {
            return Err(StateError::ConcurrentWrite);
        }
        validate_schema15(&transaction)?;
        transaction.commit().map_err(StateError::Sqlite)?;
    } else if metadata.6
        != Some(
            i64::try_from(provisional_identity.device)
                .map_err(|_| StateError::BootstrapArtifactMismatch)?,
        )
        || metadata.7
            != Some(
                i64::try_from(provisional_identity.inode)
                    .map_err(|_| StateError::BootstrapArtifactMismatch)?,
            )
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    drop(file);
    drop(database);
    if transitioned_pending {
        hook(BootstrapCheckpoint::ProvisionalReady)?;
    }
    Ok(provisional_identity)
}

pub(super) fn validate_ready_database_metadata(
    connection: &Connection,
    lease: &BootstrapLease,
    provisional_expected: BootstrapFileIdentity,
) -> Result<i64, StateError> {
    let metadata: (
        String,
        String,
        String,
        String,
        String,
        i64,
        Option<i64>,
        Option<i64>,
    ) = connection
        .query_row(
            "SELECT host_identity.host_id, host_identity.registry_generation,
                    host_operational_metadata.bootstrap_host_id,
                    host_operational_metadata.bootstrap_generation,
                    host_operational_metadata.provisional_lock_phase,
                    host_operational_metadata.provisional_lease_generation,
                    host_operational_metadata.provisional_lock_device,
                    host_operational_metadata.provisional_lock_inode
             FROM host_identity
             JOIN host_operational_metadata
               ON host_operational_metadata.singleton = host_identity.singleton
             WHERE host_identity.singleton = 1",
            [],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                    row.get(7)?,
                ))
            },
        )
        .map_err(StateError::Sqlite)?;
    if metadata.0 != lease.record.host_id
        || metadata.1 != lease.record.bootstrap_generation
        || metadata.2 != lease.record.host_id
        || metadata.3 != lease.record.bootstrap_generation
        || metadata.4 != "ready"
        || metadata.5 <= 0
        || metadata.6
            != Some(
                i64::try_from(provisional_expected.device)
                    .map_err(|_| StateError::BootstrapArtifactMismatch)?,
            )
        || metadata.7
            != Some(
                i64::try_from(provisional_expected.inode)
                    .map_err(|_| StateError::BootstrapArtifactMismatch)?,
            )
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    Ok(metadata.5)
}

pub(super) fn bootstrap_open_ready(lease: BootstrapLease) -> Result<CurrentState, StateError> {
    lease.revalidate()?;
    let root = lease.held_root_path();
    validate_current_root_entries(&root)?;
    let database_path = lease.artifact_path("host.sqlite");
    let metadata =
        exact_artifact_metadata(&database_path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    let expected = BootstrapFileIdentity {
        device: lease
            .record
            .database_device
            .ok_or(StateError::InvalidBootstrapLock)?,
        inode: lease
            .record
            .database_inode
            .ok_or(StateError::InvalidBootstrapLock)?,
    };
    if !metadata.is_file()
        || !is_private_owner_file(&metadata)
        || bootstrap_file_identity(&metadata) != expected
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    let provisional_expected = BootstrapFileIdentity {
        device: lease
            .record
            .provisional_device
            .ok_or(StateError::InvalidBootstrapLock)?,
        inode: lease
            .record
            .provisional_inode
            .ok_or(StateError::InvalidBootstrapLock)?,
    };
    let identity = read_raw_schema_identity(&database_path)?;
    ensure_current_raw_identity(identity)?;
    ensure_no_staging_database(&root)?;
    reject_current_epoch_artifacts(&root)?;
    let database = open_bootstrap_database(&lease, "host.sqlite", &database_path, expected)?;
    configure_current_connection(&database.connection)?;
    validate_schema15(&database.connection)?;
    let lease_generation =
        validate_ready_database_metadata(&database.connection, &lease, provisional_expected)?;
    let expected_contents = provisional_lock_contents(&lease.record.host_id, lease_generation)?;
    let provisional_path = lease.artifact_path(PROVISIONAL_LOCK_FILE);
    let provisional_file = open_private_provisional_file_at(
        &lease.root_directory,
        PROVISIONAL_LOCK_FILE,
        &provisional_path,
        false,
    )?;
    let opened_provisional_identity =
        validate_provisional_lock_file(&provisional_file, &provisional_path, &expected_contents)?;
    if opened_provisional_identity.device != provisional_expected.device
        || opened_provisional_identity.inode != provisional_expected.inode
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    drop(provisional_file);
    let HeldBootstrapDatabase { connection, file } = database;
    drop(file);
    lease.revalidate()?;
    let state_root = lease.root.clone();
    drop(lease);
    Ok(CurrentState {
        connection,
        root: state_root,
        mode: StateMode::Current,
    })
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct RawSchemaIdentity {
    application_id: u32,
    user_version: i64,
}

fn read_raw_schema_identity(path: &Path) -> Result<RawSchemaIdentity, StateError> {
    let metadata = exact_artifact_metadata(path)?.ok_or(StateError::MalformedHostSchema)?;
    if !metadata.is_file() || !is_private_owner_file(&metadata) {
        return Err(StateError::MalformedHostSchema);
    }
    let mut options = OpenOptions::new();
    options.read(true);
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        options.custom_flags(nix::libc::O_CLOEXEC | nix::libc::O_NOFOLLOW);
    }
    let mut file = options
        .open(path)
        .map_err(|error| StateError::io(path, error))?;
    let opened_metadata = file
        .metadata()
        .map_err(|error| StateError::io(path, error))?;
    if !opened_metadata.is_file()
        || !is_private_owner_file(&opened_metadata)
        || bootstrap_file_identity(&opened_metadata) != bootstrap_file_identity(&metadata)
    {
        return Err(StateError::MalformedHostSchema);
    }
    let mut header = Vec::new();
    std::io::Read::by_ref(&mut file)
        .take(101)
        .read_to_end(&mut header)
        .map_err(|error| StateError::io(path, error))?;
    if header.len() < 72 || &header[..16] != b"SQLite format 3\0" {
        return Err(StateError::MalformedHostSchema);
    }
    let user_version = i64::from(u32::from_be_bytes(
        header[60..64]
            .try_into()
            .map_err(|_| StateError::MalformedHostSchema)?,
    ));
    let application_id = u32::from_be_bytes(
        header[68..72]
            .try_into()
            .map_err(|_| StateError::MalformedHostSchema)?,
    );
    Ok(RawSchemaIdentity {
        application_id,
        user_version,
    })
}

/// Opens a current database relative to the held bootstrap root, validates
/// the opened descriptor against the visible path and lock identity, and only
/// then asks `SQLite` to open the already-held file through `/proc/self/fd`.
/// `SQLITE_OPEN_NOFOLLOW` is intentionally omitted for that final open: the
/// descriptor link is the authority, while the initial `openat` above is
/// no-follow and root-anchored.
pub(super) fn open_bootstrap_database(
    lease: &BootstrapLease,
    name: &str,
    path: &Path,
    expected: BootstrapFileIdentity,
) -> Result<HeldBootstrapDatabase, StateError> {
    let visible = exact_artifact_metadata(path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    if !visible.is_file()
        || !is_private_owner_file(&visible)
        || bootstrap_file_identity(&visible) != expected
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    ensure_database_sidecars_absent(path)?;
    let file = open_bootstrap_relative_file(&lease.root_directory, name, path, false).map_err(
        |error| match error {
            StateError::Io { .. } => StateError::BootstrapArtifactMismatch,
            other => other,
        },
    )?;
    validate_held_bootstrap_database_file(&file, path, expected)?;
    let sqlite_path = sqlite_held_file_path(&file)?;
    let connection = Connection::open_with_flags(
        &sqlite_path,
        OpenFlags::SQLITE_OPEN_READ_WRITE | OpenFlags::SQLITE_OPEN_NO_MUTEX,
    )
    .map_err(StateError::Sqlite)?;
    let database = HeldBootstrapDatabase { connection, file };
    validate_held_bootstrap_database_file(&database.file, path, expected)?;
    ensure_database_sidecars_absent(path)?;
    Ok(database)
}

pub(super) fn validate_held_bootstrap_database_file(
    file: &File,
    path: &Path,
    expected: BootstrapFileIdentity,
) -> Result<(), StateError> {
    let opened = file
        .metadata()
        .map_err(|error| StateError::io(path, error))?;
    let visible = exact_artifact_metadata(path)?.ok_or(StateError::BootstrapArtifactMismatch)?;
    if !opened.is_file()
        || !is_private_owner_file(&opened)
        || !visible.is_file()
        || !is_private_owner_file(&visible)
        || bootstrap_file_identity(&opened) != expected
        || bootstrap_file_identity(&visible) != expected
        || bootstrap_file_identity(&opened) != bootstrap_file_identity(&visible)
    {
        return Err(StateError::BootstrapArtifactMismatch);
    }
    Ok(())
}

pub(super) fn sqlite_held_file_path(file: &File) -> Result<PathBuf, StateError> {
    #[cfg(target_os = "linux")]
    {
        let proc_fd = Path::new("/proc/self/fd");
        if !proc_fd.is_dir() {
            return Err(StateError::InvalidBootstrapLock);
        }
        Ok(proc_fd.join(file.as_raw_fd().to_string()))
    }
    #[cfg(not(target_os = "linux"))]
    {
        let _ = file;
        Err(StateError::InvalidBootstrapLock)
    }
}

fn ensure_current_raw_identity(identity: RawSchemaIdentity) -> Result<(), StateError> {
    if identity.user_version < HOST_SCHEMA_VERSION {
        return Err(StateError::HostStateResetRequired(identity.user_version));
    }
    if identity.user_version > HOST_SCHEMA_VERSION {
        return Err(StateError::UnsupportedFutureHostSchema(
            identity.user_version,
        ));
    }
    if identity.application_id != HOST_APPLICATION_ID {
        return Err(StateError::MalformedHostSchema);
    }
    Ok(())
}

pub(super) fn open_bootstrap_relative_file(
    root_directory: &File,
    name: &str,
    path: &Path,
    create_new: bool,
) -> Result<File, StateError> {
    #[cfg(unix)]
    {
        use nix::fcntl::{OFlag, openat};
        use nix::sys::stat::Mode;
        let mut flags = OFlag::O_RDWR | OFlag::O_CLOEXEC | OFlag::O_NOFOLLOW;
        if create_new {
            flags |= OFlag::O_CREAT | OFlag::O_EXCL;
        }
        let descriptor = openat(root_directory, name, flags, Mode::from_bits_truncate(0o600))
            .map_err(|error| {
                StateError::io(path, std::io::Error::from_raw_os_error(error as i32))
            })?;
        Ok(File::from(descriptor))
    }
    #[cfg(not(unix))]
    {
        let _ = (root_directory, name, create_new);
        Err(StateError::InvalidBootstrapLock)
    }
}

pub(super) fn open_private_bootstrap_file_at(
    root_directory: &File,
    name: &str,
    path: &Path,
    create_new: bool,
) -> Result<File, StateError> {
    let before = exact_artifact_metadata(path)?;
    if let Some(metadata) = &before
        && (!metadata.is_file() || !is_private_owner_file(metadata))
    {
        return Err(StateError::InvalidBootstrapLock);
    }
    let file = open_bootstrap_relative_file(root_directory, name, path, create_new)?;
    let opened = file
        .metadata()
        .map_err(|error| StateError::io(path, error))?;
    if !opened.is_file()
        || !is_current_owner(&opened)
        || before.is_some_and(|metadata| {
            bootstrap_file_identity(&metadata) != bootstrap_file_identity(&opened)
        })
    {
        return Err(StateError::InvalidBootstrapLock);
    }
    set_private_file_permissions_handle(&file, path)?;
    let private = file
        .metadata()
        .map_err(|error| StateError::io(path, error))?;
    if !private.is_file() || !is_private_owner_file(&private) {
        return Err(StateError::InvalidBootstrapLock);
    }
    Ok(file)
}

pub(super) fn reject_current_epoch_artifacts(root: &Path) -> Result<(), StateError> {
    for name in [
        "client.sqlite",
        "client.sqlite-wal",
        "client.sqlite-shm",
        "transition.lock",
    ] {
        if exact_artifact_metadata(&root.join(name))?.is_some() {
            return Err(StateError::StateRecoveryRequired(
                StateRecoveryReason::UnknownFreshRootArtifact,
            ));
        }
    }
    Ok(())
}

pub(super) fn ensure_no_staging_database(root: &Path) -> Result<(), StateError> {
    for entry in fs::read_dir(root).map_err(|error| StateError::io(root, error))? {
        let entry = entry.map_err(|error| StateError::io(root, error))?;
        if entry
            .file_name()
            .to_str()
            .is_some_and(|name| name.starts_with(BOOTSTRAP_STAGE_PREFIX))
        {
            return Err(StateError::BootstrapArtifactMismatch);
        }
    }
    Ok(())
}

pub(super) fn ensure_bootstrap_path_absent(root: &Path, name: &str) -> Result<(), StateError> {
    if exact_artifact_metadata(&root.join(name))?.is_some() {
        return Err(StateError::BootstrapEffectUnknown);
    }
    Ok(())
}

pub(super) fn validate_current_root_entries(root: &Path) -> Result<(), StateError> {
    let mut count = 0_u16;
    for entry in fs::read_dir(root).map_err(|error| StateError::io(root, error))? {
        let entry = entry.map_err(|error| StateError::io(root, error))?;
        count = count.saturating_add(1);
        if count > 256 {
            return Err(StateError::FreshRootRejected(
                FreshRootRejection::UnknownArtifact,
            ));
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| StateError::FreshRootRejected(FreshRootRejection::UnknownArtifact))?;
        if name == BOOTSTRAP_LOCK_FILE
            || name == "host.sqlite"
            || name == PROVISIONAL_LOCK_FILE
            || name == "run"
            || name == "presentation"
            || name.starts_with(BOOTSTRAP_STAGE_PREFIX)
        {
            continue;
        }
        return Err(
            if is_retired_client_artifact(&name) || name == "transition.lock" {
                StateError::StateRecoveryRequired(StateRecoveryReason::UnknownFreshRootArtifact)
            } else {
                StateError::FreshRootRejected(FreshRootRejection::UnknownArtifact)
            },
        );
    }
    Ok(())
}

pub(super) fn ensure_database_sidecars_absent(path: &Path) -> Result<(), StateError> {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or(StateError::BootstrapArtifactMismatch)?;
    for suffix in ["-wal", "-shm", "-journal"] {
        if exact_artifact_metadata(&path.with_file_name(format!("{file_name}{suffix}")))?.is_some()
        {
            return Err(StateError::BootstrapEffectUnknown);
        }
    }
    Ok(())
}

pub(super) fn ensure_named_stage_absent(
    root: &Path,
    expected: Option<&str>,
) -> Result<(), StateError> {
    for entry in fs::read_dir(root).map_err(|error| StateError::io(root, error))? {
        let entry = entry.map_err(|error| StateError::io(root, error))?;
        let Some(name) = entry.file_name().to_str().map(ToOwned::to_owned) else {
            continue;
        };
        if name.starts_with(BOOTSTRAP_STAGE_PREFIX) && expected != Some(name.as_str()) {
            return Err(StateError::BootstrapEffectUnknown);
        }
    }
    Ok(())
}

pub(super) fn create_private_fresh_root(path: &Path) -> Result<(), StateError> {
    fs::create_dir(path).map_err(|error| StateError::io(path, error))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::{OpenOptionsExt, PermissionsExt};
        let mut options = OpenOptions::new();
        options.read(true);
        options.custom_flags(nix::libc::O_CLOEXEC | nix::libc::O_NOFOLLOW);
        let directory = options
            .open(path)
            .map_err(|error| StateError::io(path, error))?;
        let before = directory
            .metadata()
            .map_err(|error| StateError::io(path, error))?;
        if !before.is_dir() || !is_current_owner(&before) {
            return Err(StateError::FreshRootRejected(
                FreshRootRejection::NonPrivateDirectory,
            ));
        }
        directory
            .set_permissions(fs::Permissions::from_mode(0o700))
            .map_err(|error| StateError::io(path, error))?;
        let after = directory
            .metadata()
            .map_err(|error| StateError::io(path, error))?;
        if !after.is_dir()
            || !is_private_owner_directory(&after)
            || file_identity(&before) != file_identity(&after)
        {
            return Err(StateError::FreshRootRejected(
                FreshRootRejection::NonPrivateDirectory,
            ));
        }
    }
    #[cfg(not(unix))]
    {
        super::super::utils::set_private_directory_permissions(path)?;
    }
    if let Some(parent) = path.parent() {
        sync_directory(parent)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    #[cfg(target_os = "linux")]
    #[test]
    fn held_database_identity_rejects_visible_replacement() {
        use std::{fs, os::unix::fs::PermissionsExt};

        let temporary = tempfile::tempdir().unwrap();
        let root = temporary.path().join("state");
        let generator = crate::domain::RandomIdGenerator;
        drop(super::create_current(&root, &generator).unwrap());
        let root_directory = super::open_bootstrap_root_directory(&root).unwrap();
        let path = super::bootstrap_root_artifact_path(&root, &root_directory, "host.sqlite");
        let metadata = super::exact_artifact_metadata(&path).unwrap().unwrap();
        let expected = super::bootstrap_file_identity(&metadata);
        let file =
            super::open_bootstrap_relative_file(&root_directory, "host.sqlite", &path, false)
                .unwrap();

        let moved = temporary.path().join("host.sqlite.moved");
        fs::rename(root.join("host.sqlite"), &moved).unwrap();
        fs::copy(&moved, root.join("host.sqlite")).unwrap();
        fs::set_permissions(root.join("host.sqlite"), fs::Permissions::from_mode(0o600)).unwrap();

        assert!(matches!(
            super::validate_held_bootstrap_database_file(&file, &path, expected),
            Err(crate::state::StateError::BootstrapArtifactMismatch)
        ));
        assert!(moved.is_file());
    }
}
